---
title: "6306 - Final Project Brainstorm"
author: "Josh"
date: "2026-04-03"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
## NOTES
# Get a test set we can use for EDA (5-10 rows)
# - Let's say we want to plot tip amount vs fare amount
# - as long as that goes well, we can plot the millions points
# - tip amount will be response variable
# - what can we change thats going to change the tip amount
# - what variable are we interested in that are categorical vs continuous
# - zone variables are categorical not numerical
# - look for something that has strong correlation with tip amount
# - ggpairs to look at correlation among predictors

# TO DO LIST
# - LOOK passenger count

```

```{r}
# library(here)
# library(arrow)
# 
# trips_01 <- read_parquet(here("Data", "yellow_tripdata_2025-01.parquet"))
# trips_02 <- read_parquet(here("Data", "yellow_tripdata_2025-02.parquet"))
# trips_03 <- read_parquet(here("Data", "yellow_tripdata_2025-03.parquet"))
# trips_04 <- read_parquet(here("Data", "yellow_tripdata_2025-04.parquet"))
# trips_05 <- read_parquet(here("Data", "yellow_tripdata_2025-05.parquet"))
# trips_06 <- read_parquet(here("Data", "yellow_tripdata_2025-06.parquet"))
# trips_07 <- read_parquet(here("Data", "yellow_tripdata_2025-07.parquet"))
# trips_08 <- read_parquet(here("Data", "yellow_tripdata_2025-08.parquet"))
# trips_09 <- read_parquet(here("Data", "yellow_tripdata_2025-09.parquet"))
# trips_10 <- read_parquet(here("Data", "yellow_tripdata_2025-10.parquet"))
# trips_11 <- read_parquet(here("Data", "yellow_tripdata_2025-11.parquet"))
# trips_12 <- read_parquet(here("Data", "yellow_tripdata_2025-12.parquet"))
```

# Reading in Data & Sampling
```{r}
library(arrow)
library(dplyr)
library(here)
library(purrr)
library(stringr)
library(ggplot2)

files <- list.files(here("data"), pattern = "\\.parquet$", full.names = TRUE)

target_n <- 1000
n_per_file <- ceiling(target_n / length(files))

sampled_data <- map_dfr(files, function(f) {
  
  df <- read_parquet(
    f,
    col_select = c("tpep_pickup_datetime", 
                   "tpep_dropoff_datetime", 
                   "fare_amount", 
                   "trip_distance", 
                   "passenger_count", 
                   "tip_amount", 
                   "total_amount", 
                   "PULocationID", 
                   "DOLocationID", 
                   "payment_type", 
                   "extra")
  )
  
  df %>%
    slice_sample(n = min(nrow(df), n_per_file)) %>%
    mutate(
      source_file = basename(f),
      month = str_extract(basename(f), "\\d{4}-\\d{2}")
    )
})

# Checking if even sample from each of the months
sampled_data %>% count(source_file)
```

# Skim Data
```{r}
library(skimr)
skim(sampled_data)
library(DataExplorer)
plot_intro(sampled_data)
plot_missing(sampled_data)
# Note passenger_count is 22.12% missing
```

# Placeholder for Missing Values Handling
```{r}
```

# Mutate POSIX features
```{r}
# get useful info from the pickup and dropoff datetimes
library(lubridate) #intuitive functions to handle datetime data
sampled_data <- sampled_data %>%
  dplyr::mutate(
    pickup_hour <- hour(sampled_data$tpep_pickup_datetime),
    dropoff_hour <- hour(sampled_data$tpep_dropoff_datetime),
    pickup_date <- ymd_hms(sampled_data$tpep_pickup_datetime),
    pickup_weekday_num <- wday(pickup_date), # 1 = Sunday by default
    pickup_weekday_name <- wday(pickup_date, label = TRUE, abbr = TRUE)
  )

```

# Get Borough from LocationID
```{r}
#read in taxi zone lookup
zone_lookup <- read.csv("NYC_Taxi_Zones.csv") # "Location ID",	"Borough"

# if needed, clean up any leftover from previous join
# sampled_data <- sampled_data %>%
#   select(-Borough.y)

# left join pickup borough into df
sampled_data <- sampled_data %>%
  left_join(zone_lookup, by = c("PULocationID" = "Location.ID")) %>%
  rename(PUBorough = Borough) %>%
  left_join(zone_lookup, by = c("DOLocationID" = "Location.ID")) %>%
  rename(DOBorough = Borough)

head(sampled_data$Borough)
# Ignore the warning message "unknown or uninitialised column"
```

# Feature Engineering -- Trip Speed
```{r}
library(lubridate)

sampled_data <- sampled_data %>%
  dplyr::mutate(
    pickup_time  = ymd_hms(tpep_pickup_datetime),
    dropoff_time = ymd_hms(tpep_dropoff_datetime),
    # Calculate difference in minutes
    trip_minutes = interval(pickup_time, dropoff_time) / minutes(1),
    # trip quickness in miles per hour
    trip_speed_mph = 60* trip_distance / trip_minutes
  )

hist(sampled_data$trip_speed_mph)
```

# EDA
```{r}
# Looking at NAs
library(naniar)
gg_miss_var(sampled_data)
## passenger_count has a lot of NAs

str(sampled_data)

# making four columns factors
sampled_data <- sampled_data %>%
  mutate(across(c(PULocationID, DOLocationID, payment_type, month), as.factor))
# check
str(sampled_data)


# PLOTTING

ggplot(sampled_data, aes(x = trip_distance)) +
  geom_histogram(bins = 30)

ggplot(sampled_data, aes(x = month, y = fare_amount)) +
  geom_boxplot()

ggplot(sampled_data, aes(x = trip_distance, y = fare_amount)) +
  geom_point(alpha = 0.5)

ggplot(sampled_data, aes(x = trip_distance, y = fare_amount)) +
  geom_point(alpha = 0.5)

ggplot(sampled_data, aes(x = fare_amount, y = tip_amount)) +
  geom_point(alpha = 0.5)

# Creating Duration (mins) Column
df <- sampled_data %>%
  mutate(
    tpep_pickup_datetime  = as.POSIXct(tpep_pickup_datetime, format = "%Y-%m-%d %H:%M:%S"),
    tpep_dropoff_datetime = as.POSIXct(tpep_dropoff_datetime, format = "%Y-%m-%d %H:%M:%S"),
    duration_mins = as.numeric(difftime(tpep_dropoff_datetime, tpep_pickup_datetime, units = "mins"))
  )

# Looking at values per mile

df <- df %>%
  mutate(
    fare_per_mile   = if_else(trip_distance > 0, fare_amount / trip_distance, NA_real_),
    fare_per_min    = if_else(duration_mins > 0, fare_amount / duration_mins, NA_real_),
    tip_per_mile    = if_else(trip_distance > 0, tip_amount / trip_distance, NA_real_),
    tip_per_min     = if_else(duration_mins > 0, tip_amount / duration_mins, NA_real_),
    tip_pct_fare    = if_else(fare_amount > 0, 100 * tip_amount / fare_amount, NA_real_)
  )




```


